---
- name: Setup OpenVPN Server
  hosts: vpn_server
  become: yes
  vars:
    openvpn_port: 1194
    openvpn_proto: udp
    openvpn_device: tun
    vpn_subnet: 10.8.0.0
    ca_cert: "/etc/openvpn/ca.crt"
    server_cert: "/etc/openvpn/server.crt"
    server_key: "/etc/openvpn/server.key"
    dh_param: "/etc/openvpn/dh.pem"
  tasks:
    - name: Install OpenVPN and Easy-RSA
      yum:
        name:
          - openvpn
          - easy-rsa
        state: present

    - name: Copy OpenVPN server configuration
      template:
        src: templates/server.conf.j2
        dest: /etc/openvpn/server.conf
      notify:
        - restart openvpn

    - name: Create directory for Easy-RSA
      file:
        path: /etc/openvpn/easy-rsa
        state: directory

    - name: Copy Easy-RSA files
      copy:
        src: /usr/share/easy-rsa/3.0.8/
        dest: /etc/openvpn/easy-rsa/
        remote_src: yes

    - name: Initialize the PKI
      command: /etc/openvpn/easy-rsa/easyrsa init-pki
      args:
        chdir: /etc/openvpn/easy-rsa

    - name: Build CA
      command: /etc/openvpn/easy-rsa/easyrsa build-ca nopass
      args:
        chdir: /etc/openvpn/easy-rsa

    - name: Generate server certificate and key
      command: /etc/openvpn/easy-rsa/easyrsa build-server-full server nopass
      args:
        chdir: /etc/openvpn/easy-rsa

    - name: Generate Diffie-Hellman parameters
      command: /etc/openvpn/easy-rsa/easyrsa gen-dh
      args:
        chdir: /etc/openvpn/easy-rsa

    - name: Copy generated keys and certificates
      copy:
        src: "{{ item }}"
        dest: "/etc/openvpn/"
        owner: root
        group: root
        mode: '0600'
      loop:
        - "{{ ca_cert }}"
        - "{{ server_cert }}"
        - "{{ server_key }}"
        - "{{ dh_param }}"

    - name: Start and enable OpenVPN service
      systemd:
        name: openvpan@server
        state: started
        enabled: yes

  handlers:
    - name: restart openvpn
      systemd:
        name: openvpn@server
        state: restarted