---
- name: Setup OpenVPN Server
  hosts: vpn_server
  become: yes
  vars:
    openvpn_port: 1194
    openvpn_proto: udp
    openvpn_device: tun
    vpn_subnet: 10.8.0.0
  tasks:
    - name: Install OpenVPN
      yum:
        name: openvpn
        state: present

    - name: Copy OpenVPN server configuration
      template:
        src: templates/server.conf.j2
        dest: /etc/openvpn/server.conf
      notify:
        - restart openvpn

    - name: Start and enable OpenVPN service
      systemd:
        name: openvpn@server
        state: started
        enabled: yes

  handlers:
    - name: restart openvpn
      systemd:
        name: openvpn@server
        state: restarted